### ISSUE TITLE
Content is not scrolling on mobile device

### ISSUE THREAD

**Issue by mkl-strnge** [AIHelpsSoft/documentations#2] opened 2019-11-22 08:36 UTC
Iphone 7, Safari
https://wizard-salon.com.ua/video_2019-11-22_10-34-03.mp4

**Comment by Kolomiiyets** [comment] 2020-09-04 13:35
Can you reproduce this bug yet?

**Comment by Kolomiiyets** [comment] 2020-09-04 13:46
@mkl-strnge Can you reproduce this bug yet?

**Comment by Kolomiiyets** [comment] 2020-09-15 08:14
just close this issue because I don't get an answer

**Closed as completed by Kolomiiyets** 2020-09-15 08:14 UTC
Labels: bug, question, hot fix, Online Booking
